# Generated by Django 5.2.4 on 2025-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("published_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="books/covers/"),
                ),
            ],
        ),
    ]
